### ISSUE TITLE
 Installation impossible through webadmin

### ISSUE THREAD

**Issue by pyrignis** [Gredin67/mautrix_signal_ynh#2]
### Describe the bug

Installation impossible through webadmin

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.6.1 
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 0.1.1~ynh1

### Steps to reproduce

install package through webadmin  

### Expected behavior

package gets installed

### Logs

[...]

2021-07-12 17:02:41,715: DEBUG - + mkdir -p /var/log/mautrix_signal
2021-07-12 17:02:41,717: DEBUG - + python3 -m venv /opt/yunohost/mautrix_signal
2021-07-12 17:02:44,363: DEBUG - + /opt/yunohost/mautrix_signal/bin/pip3 install '/opt/yunohost/mautrix_signal/src/mautrix-signal.tar.gz[metrics,formattednumbers,qrlink]'
2021-07-12 17:02:45,932: DEBUG - Processing /opt/yunohost/mautrix_signal/src/mautrix-signal.tar.gz
2021-07-12 17:02:46,177: DEBUG -     Complete output from command python setup.py egg_info:
2021-07-12 17:02:46,177: DEBUG -     Traceback (most recent call last):
2021-07-12 17:02:46,177: DEBUG -       File "<string>", line 1, in <module>
2021-07-12 17:02:46,178: DEBUG -       File "/tmp/pip-req-build-yu75z_y2/setup.py", line 3, in <module>
2021-07-12 17:02:46,178: DEBUG -         from mautrix_signal.get_version import git_tag, git_revision, version, linkified_version
2021-07-12 17:02:46,178: DEBUG -       File "/tmp/pip-req-build-yu75z_y2/mautrix_signal/get_version.py", line 9, in <module>
2021-07-12 17:02:46,178: DEBUG -         "HOME": os.environ["HOME"],
2021-07-12 17:02:46,178: DEBUG -       File "/usr/lib/python3.7/os.py", line 678, in __getitem__
2021-07-12 17:02:46,178: DEBUG -         raise KeyError(key) from None
2021-07-12 17:02:46,178: DEBUG -     KeyError: 'HOME'
2021-07-12 17:02:46,179: DEBUG - 
2021-07-12 17:02:46,179: DEBUG -     ----------------------------------------
2021-07-12 17:02:46,183: WARNING - Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-yu75z_y2/
2021-07-12 17:02:46,259: DEBUG - + ynh_exit_properly
2021-07-12 17:02:46,260: DEBUG - + local exit_code=1
2021-07-12 17:02:46,260: DEBUG - + rm -rf /var/cache/yunohost/download/
2021-07-12 17:02:46,261: DEBUG - + '[' 1 -eq 0 ']'
2021-07-12 17:02:46,261: DEBUG - + trap '' EXIT
2021-07-12 17:02:46,262: DEBUG - + set +o errexit
2021-07-12 17:02:46,262: DEBUG - + set +o nounset
2021-07-12 17:02:46,262: DEBUG - + sleep 0.5
2021-07-12 17:02:46,763: DEBUG - + type -t ynh_clean_setup
2021-07-12 17:02:46,763: DEBUG - + ynh_clean_setup
2021-07-12 17:02:46,764: DEBUG - + true
2021-07-12 17:02:46,764: DEBUG - + exit 1
2021-07-12 17:02:47,766: ERROR - Impossible d’installer mautrix_signal : Une erreur est survenue dans le script d’installation de l’application

**Comment by pyrignis** [comment]
Installation through command line with default settings and addition of 1 local user as account administrator of the Signal bot, nets the following issues in terminal:

```sh
Choose Matrix user(s) authorized to bridge with the Signal bot (default: local): 
Info: Installing mautrix_signal...
Info: [....................] > Validating installation parameters...
Info: [....................] > Configuring firewall...
Info: [+...................] > Storing installation settings...
Info: [#++++++++++++++.....] > Installing dependencies...
Info: '/etc/apt/trusted.gpg.d/mautrix_signal.asc' wasn't deleted because it doesn't exist.
Info: [###############.....] > Creating a PostgreSQL database...
Info: [###############+....] > Setting up source files...
Info: [################....] > Configuring system user...
Info: [################+++.] > Configuring a systemd service...
Info: [###################.] > Configuring Mautrix-Bridge...
Warning:   Failed building wheel for mautrix-signal
Info: [###################.] > Configuring log rotation...
Info: [###################.] > Starting a systemd service...
Warning: ERROR:  column "signalbot" does not exist
Warning: LINE 1: UPDATE users SET admin = 1 WHERE name = signalbot;
Warning:                                                 ^
Info: [####################] > Installation of mautrix_signal completed
Success! Installation completed
```
and after that, the bot responds to the invitation request but doesn't ever seems to "read" the commands sent afterwards.

**Comment by Gredin67** [comment]
I just upgraded, can you try to upgrade from the Command Line?

**Comment by Gredin67** [comment]
please post a new issue here https://github.com/YunoHost-Apps/mautrix_signal_ynh
if remaining
